name: Run tmate on runner

on: [push, pull_request]

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
      - name: Install tmate
        run: sudo apt-get install tmate -y
      - name: Run tmate
        run: tmate -S /tmp/tmate.sock new-session -d
      - name: Print tmate SSH connection string
        run: echo "tmate -S /tmp/tmate.sock ssh \$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"
      - name: Wait for tmate to start
        run: sleep 10
