name: Start persistent tmate session on runner

on: [push, pull_request]

jobs:
  tmate:
    runs-on: self-hosted
    steps:
      - name: Install tmate
        run: sudo apt-get install tmate -y
      - name: Start tmate
        run: tmate -S /tmp/tmate.sock new-session -d
      - name: Set tmate SSH connection string
        id: ssh
        run: |
          echo "TMATE_SSH=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')" >> $GITHUB_ENV
      - name: Set tmate web URL
        id: url
        run: |
          echo "TMATE_URL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')" >> $GITHUB_ENV
      - name: Keep workflow running
        run: sleep infinity
        if: always()
    env:
      TMATE_SSH: ${{ steps.ssh.outputs.TMATE_SSH }}
      TMATE_URL: ${{ steps.url.outputs.TMATE_URL }}
